name: Build And Push Docker Image

on:
  schedule:
    # 参考 https://jasonet.co/posts/scheduled-actions/
    # note: 这里是GMT时间，北京时间减去八小时即可。如北京时间 22:30 => GMT 14:30
    # minute hour day month dayOfWeek
    - cron: '00 14 * * *' # GMT 14:00 => 北京时间 22:00
    #- cron: '30 16 * * *' # GMT 16:30（前一天） => 北京时间 00:30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        id: latest_tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
        with:
          org: 'whyour'  # Docker Hub user or organisation name
          repo: 'qinglong'  # Docker Hub repository name

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/qinglong
            ghcr.io/${{ github.repository_owner }}/qinglong
          tags: |
            type=semver,pattern={{version}},value=${{ steps.latest_tag.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.latest_tag.outputs.tag }}
            type=semver,pattern={{major}},value=${{ steps.latest_tag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            QL_STATIC_BRANCH=v${{ steps.latest_tag.outputs.tag }}
          network: host
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          context: docker/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
