name: Build And Push Docker Image for Develop Branch with Python 3.10

on:
  schedule:
    # 参考 https://jasonet.co/posts/scheduled-actions/
    # note: 这里是GMT时间，北京时间减去八小时即可。如北京时间 22:30 => GMT 14:30
    # minute hour day month dayOfWeek
    #- cron: '00 14 * * *' # GMT 14:00 => 北京时间 22:00
    - cron: '30 16 * * *' # GMT 16:30（前一天） => 北京时间 00:30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/qinglong
            ghcr.io/${{ github.repository_owner }}/qinglong
          flavor: |
            latest=auto
            suffix=-python3.10,onlatest=true
          tags: |
            type=schedule,pattern=nightly

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE=python:3.10-alpine
            QL_BRANCH=develop
            QL_STATIC_BRANCH=develop
          network: host
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          context: docker/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
